trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     name: Default
     demands: mycap

    variables:
     solution: '**/*.sln'
     buildPlatform: 'Any CPU'
     buildConfiguration: 'Release'
  
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
       restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
       solution: '$(solution)'
       platform: '$(buildPlatform)'
       configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
       platform: '$(buildPlatform)'
       configuration: '$(buildConfiguration)'
    - script: echo 'Building application'
    
- stage: Publish
  jobs:
  - job: Publish
    pool: 
     name: Default
     demands: mycapability
    steps:
    - script: echo 'Published'
    - task: PublishBuildArtifacts@1
